FROM ubuntu:18.04

WORKDIR /home/player/MyPlayer

# Installation des paquets système
RUN apt-get update && apt-get install -y \
    python3.8 \
    python3-pip \
    python3-gi \
    python3-gi-cairo \
    gir1.2-gtk-3.0 \
    gir1.2-gstreamer-1.0 \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gir1.2-gst-plugins-base-1.0 \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    libasound2 \
    gstreamer1.0-alsa \
    alsa-utils \
    libpulse0 \
    gstreamer1.0-pulseaudio \
    zlib1g-dev libtiff5-dev libjpeg8-dev libopenjp2-7-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev \
    libfribidi-dev libxcb1-dev \
    && rm -rf /var/lib/apt/lists/*

# Création de l'utilisateur pour correspondre à ton environnement
RUN useradd -m -u 1000 player && \
    mkdir -p /home/player/MyPlayer

# Copie du venv
COPY venv /opt/venv

# Copie du code en respectant la structure originale
#COPY player/src/ /home/player/MyPlayer/player/src/

#COPY player/mongodb/ /home/player/MyPlayer/player/mongodb/
COPY player/init_config_docker/ /home/player/MyPlayer/player/init_config_docker/

# Copie des libs si vraiment nécessaire
COPY player/libs /usr/lib/x86_64-linux-gnu/

# Environnement
ENV PATH="/opt/venv/bin:$PATH"
ENV HOME=/home/player


RUN mkdir -p /home/player/.Player/logs 
RUN chown -R player:player /home/player
RUN chmod -R 755 /home/player/.Player



USER player

COPY --chmod=755 /player/entrypoint.sh /player/entrypoint.sh

ENTRYPOINT ["/player/entrypoint.sh"]

CMD ["/opt/venv/bin/python3","-m","debugpy","--listen","0.0.0.0:5678","--wait-for-client","/home/player/MyPlayer/player/src/main.py","-c","/home/player/.Player/config/config-docker.ini"]