name: player

services:
  myplayer:
    container_name: myplayer
    image: myplayer
    build:
      context: /home/fredele/MyPlayer
      dockerfile: /home/fredele/MyPlayer/player/Dockerfile
      target: release

    network_mode: host

    environment:
      PULSE_SERVER: ${XDG_RUNTIME_DIR}/pulse/native

    group_add:
      - "${AUDIO_GID}"

    ports:
      - "5678:5678"  # Expose debugpy port