name: player

services:
  myplayer:
    container_name: myplayer
    image: myplayer
    build:
      context: ..
      dockerfile: ./player/Dockerfile
      target: release

    network_mode: host

    environment:
      PULSE_SERVER: ${XDG_RUNTIME_DIR}/pulse/native

    group_add:
      - "${AUDIO_GID}"

