name: player-dev

services:
  myplayer:
    container_name: myplayer
    image: myplayer-dev
    build:
      context: ..
      dockerfile: ./player/Dockerfile
      target: debug

    network_mode: host

    environment:
      PULSE_SERVER: ${XDG_RUNTIME_DIR}/pulse/native

    group_add:
      - "${AUDIO_GID}"

    ports:
      - "5678:5678"