#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -x "/opt/venv/bin/python3" ]; then
    # Docker
    PYTHON="/opt/venv/bin/python3"
else
    # Environnement local / VS Code
    PYTHON="../../venv/bin/python3"
fi

"$PYTHON" "$SCRIPT_DIR/updatelib.py"
"$PYTHON" "$SCRIPT_DIR/updatesavedqueries.py"
